#!/bin/bash

date_data=$(date "+%m/%d/%y%n")

raiz=~/unitedrpms-appstream-data
mkdir -p ${raiz}
megacopy --local "${raiz}" --remote /Root/unitedrpms/metadata/ --download
pushd ~/unitedrpms-appstream-data/
git tag ${date_data}
git push origin ${date_data}
popd
