#!/bin/bash

dnf -y install golang


date_data=$(date "+%m/%d/%y%n")

raiz=~/unitedrpms-appstream-data/
mkdir -p ${raiz}
megacopy --local "${raiz}" --remote /Root/unitedrpms/metadata/ --download
mkdir -p ~/unitedrpms-appstream-data
pushd ~/unitedrpms-appstream-data/
git tag t_est
git push origin _test
popd
